version: '2'
services:
    entidad-app:
        image: entidad
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://entidad-mysql:3306/entidad?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    entidad-mysql:
        extends:
            file: mysql.yml
            service: entidad-mysql
